name: stockapp
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  cupertino_icons: ^1.0.5
  intl: ^0.18.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Add assets section to your application
  assets:
    - assets/company_data.json  # Correct path to your JSON file
    - assets/user_stock_data.json
  # If you want to add images or other assets in the future:
  #   - images/a_dot_ham.jpeg
